mutation AddMessages($phaseId: uuid!, $parent: uuid = null, $parentIsNull: Boolean = true, $firstNumber: Int!, $numberOfMessages: Int!, $messages: [prompt_insert_input!]!) {
  makeRoomTopLevel: update_prompt(where: {section_id: {_eq: $phaseId}, _and: {number: {_gte: $firstNumber}, _and: {parent: {_is_null: true}}}}, _inc: {number: $numberOfMessages}) @include(if: $parentIsNull) {
    affected_rows
  }
  makeRoomWithinSameParent: update_prompt(where: {section_id: {_eq: $phaseId}, _and: {number: {_gte: $firstNumber}, _and: {parent: {_eq: $parent}}}}, _inc: {number: $numberOfMessages}) @skip(if: $parentIsNull) {
    affected_rows
  }

  insert_prompt(objects: $messages) {
    returning {
      id
    }
  }
}
