mutation AddQuestion($surveyId: uuid!, $number: Int!, $question: String!, $note: String = "", $type: String = "text") {
  insert_survey_question_one(object: {survey_id: $surveyId, question: $question, number: $number, note: $note, type: $type}) {
    id
  }
}
