mutation AddWorksheet($challengeId: uuid!, $number: smallint!, $long_description: String = "", $short_description: String = "") {
  insert_geogebra_worksheet_one(object: {challenge_id: $challengeId, long_description: $long_description, number: $number, short_description: $short_description}) {
    id
  }
}
