mutation DeleteMessage($id: uuid!, $number: Int!, $phaseId: uuid!) {
  delete_prompt(where: {id: {_eq: $id}}) {
    affected_rows
  }
  update_prompt(where: {section_id: {_eq: $phaseId}, _and: {number: {_gt: $number}}}, _inc: {number: -1}) {
    affected_rows
  }

}
