query GetChallenge($episodeId: uuid!) {
  challenge(where: {chapter_id: {_eq: $episodeId}}) {
    id
    long_description
    short_description
    geogebra_worksheets(order_by: {number: asc}) {
      id
      number
      ggb
      inputs
      outputs
      document
      short_description
      long_description
      challenge_id
    }
  }
}
