query GetStories {
  story(order_by: {title: asc}) {
    title
    id
    chapters(order_by: {number: asc_nulls_last}) {
      id
      title
      edit
      story {
        id
      }
    }
    edit
  }
}
