subscription RefreshEpisode($id : uuid!) {
  story_chapter_by_pk(id: $id) {
    number
    title
    specs
    sections(order_by: {number: asc_nulls_last}) {
      id
      specs
      number
      title
      meta
      topic_whitelist
      prompts(order_by: {number: asc}, where: {parent: {_is_null: true}}) {
        id
        attachment
        logic
        sender_id
        text
        type
        parent
        number
      }
    }
    story {
      id
      title
      edit
    }
    edit
  }
}
